# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6a7eb83e6b72be57b466b4267eb23a4569274fb476ea9fb86832c13a974869121200492b47890be1bbc0b6266bc5f2f96f2a4437eedbe2542a644cc77ff8942f

test:
  secret_key_base: 9a5af00c51a24f9f80845abd3f46d595b4b498c08b713a1dd37c1b50966b361a80ebb764b1928f53ab6ad20477ca7f49ebb47138492513986718de11992bfe88

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
