name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_CACHE_ALL: true
      BUNDLE_PATH: /vendor/bundle
      BUNDLE_CACHE_PATH: /vendor/bundle
      BUNDLE_BIN: /vendor/bundle
      GEM_HOME: /vendor/bundle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:5-alpine
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install ruby using .rubyversion
        uses: ruby/setup-ruby@v1

      - name: Install PostgreSQL 11 client (RADAR remove after march 2020)
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Read node version from .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Update bundler
        run: gem install bundler

      - name: Setup gem cache
        uses: actions/cache@v1
        with:
          path: /vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Get yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Bundle install
        run: |
          bundle install --jobs 4 --retry 3 --without development

      - name: Yarn install
        run: yarn --frozen-lockfile

      - name: Compile assets
        run: |
          bundle exec rails assets:precompile

      - name: Setup database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rails db:prepare

      - name: Run Specs
        run: |
          bundle exec rspec
